### PR TITLE
Another Functionality for Future Implementations

### PR DESCRIPTION
**Pull request by Just-Feeshy**
With the previous one, I somehow managed to delete the CI action.

### CODE REVIEW

**Comment by player-03** [comment]
Can you describe what functionality you're adding?

**Comment by Just-Feeshy** [comment]
I'm adding easier functionality to allow for other graphic APIs like Metal.

**Comment by Just-Feeshy** [comment]
Would it be possible to review this pull request at the earliest convenience? It's crucial for my projects as I'm extending capabilities beyond OpenGL and WebGL by integrating Vulkan support. I've been utilizing my Lime fork for more effective complexity handling during specific Graphics API compilation and binding processes. I appreciate your consideration and am excited to hear your feedback.

**Comment by Just-Feeshy** [comment]
I will close this branch due to how little documentation I provided.

**Pull request closed without merging**
