### PR TITLE
Fixed BitmapData.getPixels() to not change the image to turn it blue.

### PR DESCRIPTION
**Pull request by gunnbr**
This only happens when the BitmapData does not have an alpha component, such as from a loaded JPG.

As far as I can tell, this code should never have been here as it causes getPixels() to modify the BitmapData its getting the pixels from. It looks like either:

1. Someone was using it for testing to visually verify it was grabbing pixels from where they expected.
2. It was trying to get the alpha value in the returned pixels to 0xFF, but doing it wrong. And, that's not even necessary because without this, it already returns an alpha of 0xFF.

I also have a bunch of unit tests to go along with this change, but I can't submit those yet because they don't work on -next as that appears to use RGBA instead of ARGB like legacy does.

### CODE REVIEW

**Comment by jgranick** [comment]
The latest release should have switch `getPixels` on Lime to use ARGB instead of RGBA, let me know if this does not seem to be the case

**Comment by gunnbr** [comment]
Yeah, it works. Thought I had the latest, but I didn't. I do still see another difference between legacy and next, but I'm gathering information and will post something about that shortly.

**Comment by jgranick** [comment]
I am not sure if I recall where it crept -- it could have been in the image loading code (which might be fixed now, as we use newer lib versions) or it might have been something internal that set surface pixels (such as `bitmapData.draw`) or some combination of the `getPixel`/`setPixel` APIs, I forget

I recall a problem where an image that was supposed to not have alpha was returning alpha values other than 0xFF, for example, if you created a new BitmapData and set the `transparent` value to false, but then used `setPixels` with alpha values, this would be stored, and returned when you called `getPixels`

The masking could be done on the set call instead of the get, but perhaps get was the safest way to ensure it never, ever had this data when it was not supposed to

**Comment by gunnbr** [comment]
Okay. I just put up a pull request for some unit tests for all this. They don't currently test the case where you write different alpha values to a BitmapData with the `transparent` value set to false. I can add that in really quick though.

**Comment by gunnbr** [comment]
Oh, and I just realized I didn't say above, but this pull request fixes issue #270.

**Pull request merged**
