### PR TITLE
Don't compile `armv7` if the `architecture` excluded it.

### PR DESCRIPTION
**Pull request by MAJigsaw77**
Previously only the ndll was excluded from being added to the app, now that part of the compilation won't even happen anymore decreasing the compile time.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
hopefully that does better job in ndk r26+

**Comment by player-03** [comment]
Well now there's no guarantee that any architecture will be selected. Maybe we need something like this at the end?

```haxe
if (architectures.length == 0) architectures.push(Architecture.ARM64);
```

**Comment by MAJigsaw77** [comment]
> Well now there's no guarantee that any architecture will be selected. Maybe we need something like this at the end?
> 
> ```hx
> if (architectures.length == 0) architectures.push(Architecture.ARM64);
> ```

Right

**Comment by MAJigsaw77** [comment]
Maybe was better to also warn the user but ok

**Comment by player-03** [comment]
That would be fine too. I don't have any reasons to prefer either.

**Comment by MAJigsaw77** [comment]
I think is done

**Pull request merged**
