### PR TITLE
Assets open from wherever

### PR DESCRIPTION
**Pull request by Shallowmallow**
Before if you did 
./build/openfl/linux/bin/App

it would do
Error : [lime.utils.Preloader] ERROR: There is no asset library with an ID of "default"

### CODE REVIEW

**Comment by player-03** [comment]
This is at least partially a duplicate of #1538. Please rewrite based on the [8.1.0-Dev](https://github.com/openfl/lime/tree/8.1.0-Dev) branch.

**Comment by Shallowmallow** [comment]
Oh cool, your version seems better :)

**Comment by player-03** [comment]
Can you confirm it works for your use case?

**Comment by Shallowmallow** [comment]
Yes, just tested your commit works for me :)

**Pull request closed without merging**
