### PR TITLE
Update to the latest version of Gradle

### PR DESCRIPTION
**Pull request by MAJigsaw77**
Updating `Gradle` to the latest version can bring us support for `Java 18`

### CODE REVIEW

**Comment by player-03** [comment]
Note that you can also configure this on a per-project basis:

```xml
<config:android gradle-version="7.5.1" gradle-plugin="7.3.1" />
```

**Comment by MAJigsaw77** [comment]
> Note that you can also configure this on a per-project basis:
> 
> ```
> <config:android gradle-version="7.5.1" gradle-plugin="7.3.1" />
> ```

Ik this but will be better to update on `lime` itself, will be better for all the people, not only me in this case.

**Comment by MAJigsaw77** [comment]
The latest gradle is better then the old one

**Comment by flashultra** [comment]
Before this update maybe is good to check the compability with HaxeExtension projects ( https://github.com/HaxeExtension ) .
It is possible that most (if not all) of them will stop working.

**Comment by MAJigsaw77** [comment]
> Before this update maybe is good to check the compability with HaxeExtension projects ( https://github.com/HaxeExtension ) . It is possible that most (if not all) of them will stop working.

Idk, the gradle from here is from 2019, I think we must update to something new tough.

**Comment by MAJigsaw77** [comment]
From what I've saw, from all their `build.gradle` files must replace `compile` option with `api` or `implementation`, that's all.

**Comment by flashultra** [comment]
I think there was also a dependency from AndroidX libraries and maybe something else.  I'm not against such update, but I'm just warning about possible problems in the future with extensions . If anyone want could make a check .

**Comment by MAJigsaw77** [comment]
> I think there was also a dependency from AndroidX libraries and maybe something else. I'm not against such update, but I'm just warning about possible problems in the future with extensions . If anyone want could make a check .

I used `AndroidX` with this gradle, there was no ploblems.

**Comment by player-03** [comment]
Plus AndroidX is related to the target SDK version, not the Gradle version. If you're still targeting an old SDK, then you don't need it.

**Comment by MAJigsaw77** [comment]
I still think we must update `Gradle`, the current version of gradle that lime uses is from 2019, it's pearty old.

**Comment by player-03** [comment]
I knew this felt familiar! Closing this because we already have #1500.

**Comment by MAJigsaw77** [comment]
Um?

**Comment by MAJigsaw77** [comment]
Nvm

**Pull request closed without merging**
