### PR TITLE
Added `android:appCategory`.

### PR DESCRIPTION
**Pull request by MAJigsaw77**
This pr is basically making an app able to be detected as a game on `android`.

### CODE REVIEW

**Comment by MAJigsaw77** [comment]
Is there anything wrong with the pr?

**Comment by player-03** [comment]
The implementation looks fine, but it seems [`isGame` is deprecated](https://developer.android.com/guide/topics/manifest/application-element#isGame).

**Comment by MAJigsaw77** [comment]
> The implementation looks fine, but it seems [`isGame` is deprecated](https://developer.android.com/guide/topics/manifest/application-element#isGame).

Maybe i should implement that instead

**Comment by MAJigsaw77** [comment]
@player-03 what should be as default value?

**Comment by joshtynjala** [comment]
> what should be as default value?

The Android docs say this:

> Only define this value for apps that fit well into one of the specific categories.

With that in mind, by default, you shouldn't set it to any value. Just skip it entirely.

**Comment by MAJigsaw77** [comment]
Is ok?

**Comment by MAJigsaw77** [comment]
Will this be pushed?

**Comment by player-03** [comment]
What do you think of #1735 as a solution?

**Comment by MAJigsaw77** [comment]
> What do you think of #1735 as a solution?

It's better then this implementation

**Comment by MAJigsaw77** [comment]
You can close this if you want

**Comment by player-03** [comment]
Might leave this open until we get more feedback on my version. Edit: merged.

**Pull request closed without merging**
