### PR TITLE
fix wierd audio stuttering on windows

### PR DESCRIPTION
**Pull request by Vortex2Oblivion**
after updating to lime 8.0.1 yesterday, i was experiencing weird audio issues where it would stutter for a tiny bit at random points, reverting  #1558  *seems* to fix it
After some testing with this change I haven't really had any issues

### CODE REVIEW

**Comment by player-03** [comment]
@justin-espedal Can you take a look at this?

**Comment by justin-espedal** [comment]
This isn't exactly helpful if it's just going back to the previous behavior, which was also buggy.

The only platform the previous behavior was definitively wrong for was iOS. If somebody can't figure out exactly what's going wrong here, perhaps some platform-specific code could be used as a crutch?

What platform are you experiencing issues on, @Vortex2Oblivion?

**Comment by Vortex2Oblivion** [comment]
im on windows c++

**Comment by player-03** [comment]
Did you mean to close this?

**Comment by player-03** [comment]
@Vortex2Oblivion Should we assume there's no more need to revert #1558?

**Pull request closed without merging**
