### PR TITLE
Fix ImageDataUtil.copyPixels crash on Hashlink

### LINKED ISSUE #2754: `BitmapData`: `copyPixels` crashes on HL
Observed on openfl 9.4.0 with lime 8.2.1

```hx
package;

import openfl.display.BitmapData;

class Main extends openfl.display.Sprite {
	public function new () {
		super ();
		
		final fullFrame = new BitmapData(10, 10, true, 0x0);
		final result = new BitmapData(10, 10, true, 0x0);
		final mask = new BitmapData(10, 10, true, 0xFFffffff);
		
		result.copyPixels(result, result.rect, new openfl.geom.Point(), mask);
	}	
}
```

Error:
> booboo@Georges-MacBook-Pro DisplayingABitmap % lime test hl -debug -clean
[debug] Using haxelib from "/usr/local/lib/haxe/lib/haxelib/4,0,3/"
SIGNAL 11
lime._internal.graphics.$ImageDataUtil.copyPixels(lime/_internal/graphics/ImageDataUtil.hx:314)
lime.graphics.Image.copyPixels(lime/graphics/Image.hx:490)
openfl.display.BitmapData.copyPixels(openfl/display/BitmapData.hx:720)
$Main.__constructor__(Main.hx:28)
$DocumentClass.__constructor__(ApplicationMain.hx:308)
$ApplicationMain.start(ApplicationMain.hx:218)
$ApplicationMain.~create.2(ApplicationMain.hx:121)
lime.app._Event_Void_Void.dispatch(lime/_internal/macros/EventMacro.hx:91)
openfl.display.Preloader.display_onUnload(openfl/display/Preloader.hx:101)
openfl.text.TextField.~this_onMouseDown.0(lime/app/Module.hx:0)
openfl.events.EventDispatcher.__dispatchEvent(openfl/events/EventDispatcher.hx:478)
openfl.display.DisplayObject.__dispatchEvent(openfl/display/DisplayObject.hx:1475)
openfl.display.DisplayObject.__dispatchWithCapture(openfl/display/DisplayObject.hx:1536)
openfl.display.DisplayObject.dispatchEvent(openfl/display/DisplayObject.hx:1193)
openfl.display.DefaultPreloader.onLoaded(openfl/display/Preloader.hx:213)
openfl.display.DefaultPreloader.this_onComplete(openfl/display/Preloader.hx:252)
openfl.text.TextField.~this_onMouseDown.0(lime/app/Module.hx:0)
openfl.events.EventDispatcher.__dispatchEvent(openfl/events/EventDispatcher.hx:478)
openfl.display.DisplayObject.__dispatchEvent(openfl/display/DisplayObject.hx:1475)
openfl.display.DisplayObject.__dispatchWithCapture(openfl/display/DisplayObject.hx:1536)
openfl.display.DisplayObject.dispatchEvent(openfl/display/DisplayObject.hx:1193)
openfl.display.Preloader.start(openfl/display/Preloader.hx:48)
$ApplicationMain.~create.1(ApplicationMain.hx:118)
lime.app._Event_Void_Void.dispatch(lime/_internal/macros/EventMacro.hx:91)
lime.utils.Preloader.start(lime/utils/Preloader.hx:220)
lime.utils.Preloader.updateProgress(lime/utils/Preloader.hx:309)
lime.utils.Preloader.loadedAssetLibrary(lime/utils/Preloader.hx:204)
lime.utils.Preloader.~updateProgress.1(lime/utils/Preloader.hx:289)
openfl.display.Loader.~loader_onComplete.1(lime/app/Module.hx:0)
lime.app.Promise.complete(lime/app/Promise.hx:108)
openfl.utils.$Assets.~loadSound.3(lime/app/Module.hx:0)
lime.app.Future.onComplete(lime/app/Future.hx:130)
lime.app.Promise.completeWith(lime/app/Promise.hx:126)
lime.utils.$Assets.~loadLibrary.3(lime/utils/Assets.hx:476)
lime.utils.$Assets.~loadLibrary.4(lime/app/Module.hx:0)
lime.app.Promise.complete(lime/app/Promise.hx:108)
openfl.utils.$Assets.~loadSound.3(lime/app/Module.hx:0)
lime.app.Future.onComplete(lime/app/Future.hx:130)
lime.app.Future.~then.2(lime/app/Future.hx:277)
lime.app.Promise.complete(lime/app/Promise.hx:108)
lime.net._HTTPRequest_Bytes.~load.3(lime/net/HTTPRequest.hx:118)
openfl.utils.$Assets.~loadBytes.1(lime/app/Module.hx:0)
lime.app.Promise.complete(lime/app/Promise.hx:108)
lime._internal.backend.native.$NativeHTTPRequest.localThreadPool_onComplete(lime/_internal/backend/native/NativeHTTPRequest.hx:452)
lime._internal.backend.native.NativeHTTPRequest.~loadData.1(lime/app/Module.hx:0)
lime.app._Event_Dynamic_Void.dispatch(lime/_internal/macros/EventMacro.hx:91)
lime.system.ThreadPool.__update(lime/system/ThreadPool.hx:573)
lime.app._Event_Int_Void.dispatch(lime/_internal/macros/EventMacro.hx:91)
lime._internal.backend.native.NativeApplication.handleApplicationEvent(lime/_internal/backend/native/NativeApplication.hx:176)
lime._internal.backend.native.NativeApplication.exec(lime/_internal/backend/native/NativeApplication.hx:147)
lime.app.Application.exec(lime/app/Application.hx:150)
openfl.display.Application.exec(openfl/display/Application.hx:130)
$ApplicationMain.create(ApplicationMain.hx:137)
$ApplicationMain.main(ApplicationMain.hx:26)
.init(?:1)
booboo@Georges-MacBook-Pro DisplayingABitmap %

### PR DESCRIPTION
**Pull request by ACrazyTown**
On C++ when a passed Vector2 instance is null, it'll just make it (0, 0) on the C++ side: https://github.com/openfl/lime/blob/0b08e7fa61371a962c114bc52d28ccb42913a68f/project/src/math/Vector2.cpp#L31-L41

Unlike C++, on Hashlink there's no failsafe for if the Vector2 instance is null, it'll just pass it further to `ImageDataUtil::copyPixels` causing an access violation. This PR checks if we're passing in a null Vector2 on the Haxe side, and makes a new object if we are. I assume this is better than making it on the C++ side but please correct me if I'm wrong

Fixes: https://github.com/openfl/openfl/issues/2754

### CODE REVIEW

**Comment by joshtynjala** [comment]
Both hxcpp and HashLink share Lime's C++ code, so I would prefer if null checks for both targets were consistently all in C++ or all in Haxe.

Looking at some other C++ code in Lime, I suspect that a null pointer will be 0 for HashLink.

Maybe something like this is all that's needed?

```cpp
if (vec && !val_is_null (vec)) { 
```

**Comment by ACrazyTown** [comment]
I'm confused because Lime only seems to make C++ objects when compiling for C++/native:
https://github.com/openfl/lime/blob/0b08e7fa61371a962c114bc52d28ccb42913a68f/project/src/ExternalInterface.cpp#L2035-L2042
When targeting Hashlink it just directly passes the arguments from Haxe:
https://github.com/openfl/lime/blob/0b08e7fa61371a962c114bc52d28ccb42913a68f/project/src/ExternalInterface.cpp#L2047-L2059
Where would your fix go? I thought about checking if the pointer was null on the C++ side and then making an object there but I'm not completely sure if that has any negative effect? Would that have to get manually freed since it was made on the C++ side?

**Comment by joshtynjala** [comment]
If Vector2.cpp isn't the correct place, that's totally fine. I made sure to say "Maybe something like" to be clear that I was not suggesting exactly what you need to do. I haven't worked on that particular code, so you are probably more familiar with how it works than I am at this moment.

Perhaps you could add a check in hl_image_data_util_copy_pixels. Maybe something like this:

```cpp
if (!destPoint) {

     destPoint = Vector2(0, 0);

}
```

**Comment by joshtynjala** [comment]
Note: I don't frequently work with C++, and I did not try that code through a compiler. As before, it's more to give you an idea of where to look, and you can fiddle with getting the right syntax.

I just realized that it's probably a pointer, so maybe more like:

```
if (!destPoint) {

     destPoint = new Vector2(0, 0);

}
```

And then you probably need to delete it after, if it wasn't passed in from Haxe.

**Comment by ACrazyTown** [comment]
> If Vector2.cpp isn't the correct place, that's totally fine. I made sure to say "Maybe something like" to be clear that I was not suggesting exactly what you need to do.

Sorry, I wasn't exactly sure what you meant so just wanted to clarify. 

I pushed a commit where the function will now allocate a temporary `Vector2` object (this is what the hxcpp version does as well) that gets used if the passed `Vector2*` from Haxe is null. It'll get automatically cleaned up when it goes out of scope.
This is a bit more simpler than managing pointers

**Comment by joshtynjala** [comment]
That looks like we're on the right track. If I may suggest one last tweak, I think that we should avoid allocating tempPoint when it's not needed.

This should probably work:

```cpp
Vector2* _alphaPoint = alphaPoint;

if (!_alphaPoint) {

	Vector2 tempPoint = Vector2(0, 0);
	_alphaPoint = &tempPoint;

}
```

**Comment by ACrazyTown** [comment]
Should be good to go now

**Comment by trnzk** [comment]
This kind of usage can cause issues because you’re assigning the address of a local variable (tempPoint) to a pointer. Once the block ends, the local variable goes out of scope, leaving the pointer pointing to invalid memory, which can lead to undefined behavior.

**Comment by player-03** [comment]
I'd be worried about that too.

**Comment by ACrazyTown** [comment]
> This kind of usage can cause issues because you’re assigning the address of a local variable (tempPoint) to a pointer. Once the block ends, the local variable goes out of scope, leaving the pointer pointing to invalid memory, which can lead to undefined behavior.

So should I just set the pointer to `nullptr`? Or alternatively do something like this:
```cpp
if (!alphaImage) { 

    ImageDataUtil::CopyPixels (image, sourceImage, sourceRect, destPoint, NULL, NULL, mergeAlpha); 

} else { 

    if (!alphaPoint) {

        Vector2 tempAlphaPoint = Vector2(0, 0);
        ImageDataUtil::CopyPixels (image, sourceImage, sourceRect, destPoint, alphaImage, &tempAlphaPoint, mergeAlpha); 

    } else {

        ImageDataUtil::CopyPixels (image, sourceImage, sourceRect, destPoint, alphaImage, alphaPoint, mergeAlpha); 

    }

}
 	
```

**Comment by joshtynjala** [comment]
> Or alternatively do something like this

That seems good to me.

**Comment by trnzk** [comment]
I think it was fine except for the last commit. ```Vector2 tempPoint(0, 0);``` uses the stack and I believe it has negligible overhead considering what the function does.

**Comment by ACrazyTown** [comment]
Do I roll back to https://github.com/openfl/lime/pull/1875/commits/824da265a89ce99f627db2e8d633d9bcad67dea2 or do I proceed with the suggestion I made earlier? 😅 Not sure where to go from here...

**Comment by joshtynjala** [comment]
Go with this one:

```haxe
if (!alphaImage) { 

    ImageDataUtil::CopyPixels (image, sourceImage, sourceRect, destPoint, NULL, NULL, mergeAlpha); 

} else { 

    if (!alphaPoint) {

        Vector2 tempAlphaPoint = Vector2(0, 0);
        ImageDataUtil::CopyPixels (image, sourceImage, sourceRect, destPoint, alphaImage, &tempAlphaPoint, mergeAlpha); 

    } else {

        ImageDataUtil::CopyPixels (image, sourceImage, sourceRect, destPoint, alphaImage, alphaPoint, mergeAlpha); 

    }

}
```

**Pull request merged**
