### PR TITLE
Use `getDisplayMetrics()` to find screen DPI on Android.

### PR DESCRIPTION
**Pull request by MAJigsaw77**
Title

### CODE REVIEW

**Comment by player-03** [comment]
I'd say it's safe to use `getRealMetrics()` without checking. `JELLY_BEAN_MR1` corresponds to SDK 17, and as of #1519, Lime is no longer compatible with SDKs below 21. Plus, Google dropped support for that version in September 2021.

**Comment by MAJigsaw77** [comment]
A ok

**Comment by MAJigsaw77** [comment]
@player-03 done

**Comment by MAJigsaw77** [comment]
I thought this won't be pushed, that's why I closed it .___.

**Comment by Dimensionscape** [comment]
I haven't looked at it personally yet, but sometimes it just takes us forever to completely vet some prs. If you're getting feedback, its typically a good sign.

**Comment by MAJigsaw77** [comment]
Ok

**Pull request merged**
