### PR TITLE
Add Method to override Electron Main Process entry class

### PR DESCRIPTION
**Pull request by peteshand**
When targeting electron the Main Process entry class is automatically generated based off
~/lime/templates/electron/haxe/ElectronSetup.hx

In some cases it may be desirable to override this class with something custom.

This pull request addresses this by allowing the user to define an override class in the lime project.xml file as follows:

```
// add a new template dir reference
<templatePath name="./template" />

// add a reference to the Main Process entry haxe class
<config:electron electron-main="ElectronMainOverride" />
```

### CODE REVIEW

**Comment by peteshand** [comment]
Does anyone have any issues to this PR?
If not can you please merge.

**Comment by jgranick** [comment]
Can the user override with the template system already?

1. Create "templates/electron/haxe/ElectronSetup.hx"
2. Add `<templates path="templates" />` to project

This is how you override `ApplicationMain` or other files, currently

**Comment by peteshand** [comment]
Hmmm nope, doesn't appear to work.

**Comment by jgranick** [comment]
I see the following code:

```haxe
			ProjectHelper.recursiveSmartCopyTemplate (project, "electron/template", destination, context);

			if (project.app.main != null) {

				ProjectHelper.recursiveSmartCopyTemplate (project, "electron/haxe", targetDirectory + "/haxe", context, true, false);
				ProjectHelper.recursiveSmartCopyTemplate (project, "electron/hxml", targetDirectory + "/haxe", context);

			}
```

So this should resolve `<template />` paths in order, like class paths. That means you will need to add your `<template />` tag after including OpenFL/Lime, not before, in order to resolve after.

The file will also have to be a duplicate of the Lime version, plus tweaks, in order for it to work properly

**Comment by peteshand** [comment]
Thanks for the pointers, The issue turned out to be due to the fact that I copy and pasted from above
```
Add <templates path="templates" /> to project
```

should be
```
Add <template path="templates" /> to project
```

**Pull request closed without merging**
