### PR TITLE
setPixels amend

### PR DESCRIPTION
**Pull request by peteshand**
This brings the lime setPixels method more closely in line with the way the Flash bitmapData.setPixels method work.

### CODE REVIEW

**Comment by jgranick** [comment]
Should it stop writing if it is going to overflow, or should it resize the target ByteArray in order to be large enough?

**Comment by peteshand** [comment]
Hey @jgranick. Yeah actually you're right there. If the byteArray is not long enough extra 0x0 data should be added to fill the rest of the bitmapdata. I've amended my branch

**Comment by peteshand** [comment]
any update on merging this?

**Comment by jgranick** [comment]
I just gave this a try, on Flash Player, it throws an "End of file" error if the `ByteArray` is not large enough. I had a solution worked up, but since Flash is throwing an error, I think we'll leave it as-is.

Please let me know if I'm missing a test case where Flash does exhibit this behavior. Thank you :smile:

**Pull request closed without merging**
