### PR TITLE
Define `PLATFORM` and `PLATFORM_NUMBER` based on the minimum `Android` SDK Version.

### PR DESCRIPTION
**Pull request by MAJigsaw77**
This PR updates `PLATFORM` and adds `PLATFORM_NUMBER` to match with the project's minimum Android SDK version, moving away from the previous hardcoding of `android-21`.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by MAJigsaw77** [comment]
@player-03 May i get a review on this pr?

**Comment by dimensionscape** [comment]
Does this break any existing workflow?

**Comment by MAJigsaw77** [comment]
> Does this break any existing workflow?

I don't think it would break anything. I've tested this on a project and it works just fine.

**Comment by dimensionscape** [comment]
> > Does this break any existing workflow?
> 
> I don't think it would break anything. I've tested this on a project and it works just fine.

Wont developers need to include these in their project xml now?

**Comment by MAJigsaw77** [comment]
> > > Does this break any existing workflow?
> > 
> > 
> > I don't think it would break anything. I've tested this on a project and it works just fine.
> 
> Wont developers need to include these in their project xml now?

Noup, using `project.config.getInt("android.minimum-sdk-version", 21);` makes it so 21 is the default value if theres no version found within project.xml

**Comment by dimensionscape** [comment]
Sounds good. PR to the correct 8.3 branch though.

**Comment by MAJigsaw77** [comment]
I changed the base branch to `8.3.0-Dev`.

**Comment by MAJigsaw77** [comment]
Uh, i think i broke something, I'll close this and change the branch

**Pull request closed without merging**
