### PR TITLE
Fixes copyPixels mergeAlpha

### PR DESCRIPTION
**Pull request by mrcdk**
Fixes issue https://github.com/openfl/openfl/issues/618

### CODE REVIEW

**Comment by mrcdk** [comment]
The only problem is that the cpp code doesn't work on windows. Haxe code does.

**Comment by larsiusprime** [comment]
Confirmed this fixes next/neko. Testing windows/cpp now, if it's confirmed broken as mrcdk says I'll look into a patch.

**Comment by larsiusprime** [comment]
Did some digging:
- ImageDataUtil.hx: before the CFFI call, sourceImage.transparent is true
- ImageDataUtil.cpp: sourceImage->transparent is now false

Something in the conversion process is setting transparent from true to false, which makes the cpp part of the code use the first if block (don't merge) instead of the else block, b/c it thinks the image is opaque.

**Comment by mrcdk** [comment]
@jgranick can you check that I haven't messed up anything with the last change?

**Pull request merged**
