### PR TITLE
fix electron hxml template files

### PR DESCRIPTION
**Pull request by peteshand**

### CODE REVIEW

**Comment by Gama11** [comment]
Why `dce no`?

**Comment by peteshand** [comment]
yes, no dce for Electron.hx

**Comment by peteshand** [comment]
can someone merge this

**Comment by jgranick** [comment]
@peteshand Should we do a `@:keep` on the Electron extern file? Is that the issue? It would be nice to know what underlying issue this fixes. Thanks :smile:

**Comment by peteshand** [comment]
Hey, sorry about the delayed reply. yeah maybe `-dce no` is a bit overkill... the more important change is removing `::HAXE_FLAGS::` from the ElectronSetup compile as keeping this can cause runtime error, I'm mainly seem this when I've including swf assets

**Pull request closed without merging**
