### PR TITLE
fixed: legacy word-wrapped TextFields would sometimes leave an extra empty line below

### PR DESCRIPTION
**Pull request by ProPuke**
disclaimer: I just pushed buttons and this worked (fixed my test cases, and did not break any text not displaying the bug). I actually have no idea what I'm doing.

### CODE REVIEW

**Comment by jgranick** [comment]
Thanks! Just cherry-picked the commit :smile:

**Comment by ProPuke** [comment]
xD (I don't know how to make git not messy! D:)

**Comment by jgranick** [comment]
This might help :smile:

http://stackoverflow.com/questions/8134960/how-to-revert-master-branch-to-upstream

**Comment by ProPuke** [comment]
Cheers :]

So.. Turns out this "fix" is actually wrong. It was a higher-level problem with another library and this only masked the problem :( This change is actually incorrect (hey, I did include a disclaimer!)

Could this be reverted? Sorry! (now I've made more mess)

**Pull request closed without merging**
