### PR TITLE
[legacy] Add finger touch events to SDL2Stage

### PR DESCRIPTION
**Pull request by PVince81**
Fix for https://github.com/openfl/lime/issues/360

Tested on a Dell XPS 13 with touchscreen on Linux with XInput2 driver.

Please note that this also requires changing SDL_Config in "project/lib/sdl" to enable XInput2, as follows:
```
diff --git a/include/configs/linux/SDL_config.h b/include/configs/linux/SDL_config.h
index 99b06c2..ba75343 100644
--- a/include/configs/linux/SDL_config.h
+++ b/include/configs/linux/SDL_config.h
@@ -274,14 +274,14 @@
 #define SDL_VIDEO_DRIVER_X11_DYNAMIC_XEXT "libXext.so.6"
 /* #undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XCURSOR */
 /* #undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XINERAMA */
-/* #undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2 */
+#define SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2 "libXi.so.6"
 /* #undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XRANDR */
 /* #undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XSS */
 /* #undef SDL_VIDEO_DRIVER_X11_DYNAMIC_XVIDMODE */
 /* #undef SDL_VIDEO_DRIVER_X11_XCURSOR */
 /* #undef SDL_VIDEO_DRIVER_X11_XINERAMA */
-/* #undef SDL_VIDEO_DRIVER_X11_XINPUT2 */
-/* #undef SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH */
+#define SDL_VIDEO_DRIVER_X11_XINPUT2 1
+#define SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH 1
 /* #undef SDL_VIDEO_DRIVER_X11_XRANDR */
 /* #undef SDL_VIDEO_DRIVER_X11_XSCRNSAVER */
 #define SDL_VIDEO_DRIVER_X11_XSHAPE 1
```

As I'm just beginning with lime/openfl I'm not sure whether this patch would have side effects on regular single pointer apps/games.

Also it would be cool if someone could try this on a Windows machine with touchscreen (might need to add more "defines" and also add `if defined(HX_WINDOWS)` in SDL2Scene). :smile:

### CODE REVIEW

**Comment by PVince81** [comment]
I tested this using the flixel-demo "Multitouch" :smile:

**Comment by Type1J** [comment]
Could you post a test app with a project.xml? I can test on Windows 8.1 with a touch screen.

**Comment by PVince81** [comment]
@Type1J I have added changes for Windows, I hope it can make it work.

For a test app, install the flixel-demos package and compile the MultiTouch demo: flixel-demos/1,1,2/Input/Multitouch
(you can also find it here: https://github.com/HaxeFlixel/flixel-demos/tree/dev/Input/Multitouch)

**Comment by PVince81** [comment]
For Linux:

After checking out the branch from this PR and also the one from https://github.com/native-toolkit/sdl/issues/3 in "project/lib/sdl", rebuild lime:
`lime rebuild linux -64 -clean -release -Dlegacy` (I often forgot the legacy option...)

Then compile the MultiTouch example from https://github.com/HaxeFlixel/flixel-demos/tree/dev/Input/Multitouch with:
`lime test linux -64`

I'm still confused about OpenFL hybrid/legacy/whatever. This PR is for lime legacy.
I wonder where I should submit another patch to make multitouch work for "regular" openfl/lime. Would be nice if someone could point me there.

Note that in non-legacy mode multitouch does not work on Linux.

**Comment by jgranick** [comment]
Legacy is a combination of the old backend and OpenFL higher level code. The new code has Lime 2 and the OpenFL layer is written. Hybrid uses Lime 2, but has the older OpenFL level code. At this level, the C++ dispatch from Lime 2 would make it available to both hybrid or regular OpenFL

**Comment by PVince81** [comment]
@jgranick is there a documentation or diagram that explains this ? Might be worth adding one to the README or wiki to avoid confusion for newcomers. :smile:

**Pull request merged**
