### PR TITLE
Tweak audio behavior on iOS and Windows.

### LINKED ISSUE #1638: audio issues in lime 8.0.1
I've been experiencing an issue where audio will cut out for like half a second and then come back on with like a static noise in between
i downgraded my lime to 8.0.0 and it seemed to fix the issue.
anyone else having this problem?

### PR DESCRIPTION
**Pull request by player-03**
#1558 made some changes to fix an audio issue on iOS. However, in #1638, @Vortex2Oblivion reported that this caused a new error on Windows. This pull request simply reverts #1558 on non-iOS platforms. 

This isn't a perfect solution, but it should work until someone figures out the root cause of one or both errors.

### CODE REVIEW

**Comment by player-03** [comment]
I wonder if #1009 is related to all this, but am not prepared to spend the time to figure it out right now.

**Comment by player-03** [comment]
I wonder, does anyone else experience audio issues (static, cutting out, etc.) when targeting Windows C++? So far only one person reported this behavior, and he silently withdrew the issue.

**Comment by joshtynjala** [comment]
I keep meaning to try to reproduce the original issue and test the PR, but I haven't had the time yet.

**Comment by joshtynjala** [comment]
I tried various ogg and wav files that I had laying around with Windows c++ today, but I could not reproduce the issue.

**Comment by player-03** [comment]
The original reporter long since closed their issue, and no one else reported it after nine months, so I think it should be good as-is.

**Pull request closed without merging**
