### PR TITLE
Fixed JS Image issue when using the genes library to compile ES modules

### PR DESCRIPTION
**Pull request by andresa88**
Need to explicitly use:

new window.Image() 

otherwise it will create a lime Image object.

### CODE REVIEW

**Comment by joshtynjala** [comment]
Are you sure that this change is necessary? The original code is this:

```haxe
var image = new JSImage();
```

And `JSImage` is explicitly set as an alias of `js.html.Image` in the imports.

```haxe
import js.html.Image as JSImage;
```

It should be impossible for the generated JS to use `lime.graphics.Image` in this context instead. There would be a conflict between `js.html.Image` and `lime.graphics.Image` here only if the constructor call was `new Image()` instead of `new JSImage()`.

This seems more like a bug in genes.

**Comment by player-03** [comment]
I think Andres might be right. Looking at the output, [`new js.html.Image()` in Haxe becomes `new Image()` in JavaScript](https://try.haxe.org/#EC27F340). Normally, this creates a standard image element.

```haxe
class Test {
  static function main() {
    trace(new js.html.Image()); //[object HTMLImageElement]
  }
}
```

But as soon as we define our own `Image` class, [it shadows the standard one](https://try.haxe.org/#23232f8b).

```haxe
class Test {
  static function main() {
    trace(new js.html.Image()); //[not HTMLImageElement]
  }
}

@:keep
class Image {
  public inline function new() {
  }
  
  public inline function toString():String {
		return "[not HTMLImageElement]";
  }
}
```

There might still be a better workaround. And if there is, we should apply that in the [two other locations](https://github.com/openfl/lime/commit/d806b27b1b0189bc4467915c453cf0ca60c870b0) this code is used.

**Comment by joshtynjala** [comment]
Oh yes, I see. It slipped by mind that the fully-qualified `js.html.Image` wouldn't persist in JS. If there's another unqualified `Image` symbol in scope (which there seems to be, since `lime.graphics.Image` is imported), it will shadow the native JS API, as you said.

This seems like the correct solution to me.

**Comment by player-03** [comment]
Is this correct, though? `HTML5HTTPRequest` always imports `lime.graphics.Image`, so why do we call `new JSImage()` under any circumstances? Why not always call `new window.JSImage()`?

**Comment by player-03** [comment]
Also, I don't think classes are scoped in the JS output. Pretty sure that if `lime.graphics.Image` is compiled at all (i.e., not removed by DCE), it's available at the top level.

**Comment by joshtynjala** [comment]
If I remember correctly, `new JSImage()` works correctly with the Haxe compiler's default JS output because it adds more qualification than the alternative JS output generated by genes (and probably hxgenjs too). I think the Haxe compiler generates an identifier for `lime.graphics.Image`, like `lime_graphics_Image`, so it doesn't conflict.

**Comment by player-03** [comment]
Oh right, it probably does. So as long as you provide a package (unlike try.haxe.org), you can't shadow the type.

**Comment by player-03** [comment]
> I'd still like to get rid of the conditional compilation.

Done. (Took a couple tries to get it right...)

**Comment by joshtynjala** [comment]
Looks good to me!

**Comment by andresa88** [comment]
Thank you both! The additional commits work for me.

**Pull request merged**
