### PR TITLE
Use `namespace` for gradle projects to fix deprecation warnings.

### PR DESCRIPTION
**Pull request by MAJigsaw77**
This pr updates all `Gradle` project files to use `namespaces`, fixing deprecation warnings.

### CODE REVIEW

**Comment by MAJigsaw77** [comment]
This pr is splitted from #1795.

**Comment by player-03** [comment]
Hmm. Based on the documentation I was worried that this would break compatibility with AGP < 7.3, but after testing, it looks like something else already broke compatibility with those versions. So I guess it's fine?

**Comment by MAJigsaw77** [comment]
@player-03 Will this be pushed?

**Comment by player-03** [comment]
I looked at it again and despite a warning, the correct namespace string ended up in the correct place even on AGP 7.0.2. So it seems there was some level of support in earlier versions.

**Pull request merged**
