### PR TITLE
New IOS "insecure-http-allowed" xml option

### PR DESCRIPTION
**Pull request by aW4KeNiNG**
New option commented [here](http://community.openfl.org/t/modify-info-plist/7270)

It avoids the problem `App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.`

You can accept all domains with `<ios insecure-http-allowed="*"/>` or custom domains (subdomains included) with `<ios insecure-http-allowed="www.domain1.com|domain2.org"/>`

### CODE REVIEW

**Comment by tanis2000** [comment]
@jgranick this should be merged upstream as it's a needed configuration if you want to deploy an app on the App Store.

**Comment by tanis2000** [comment]
@aW4KeNiNG the new insecure-http-allowed option should be documented somewhere as well IMHO

**Comment by aW4KeNiNG** [comment]
Yeah. But i don't know where i can write the information.

**Comment by aW4KeNiNG** [comment]
I have seen that the PR #752 (already merged) is a similar solution, but it isn't customizable by the user like this one.

**Comment by ibilon** [comment]
This PR does indeed look better, and doesn't activate `NSAllowsArbitraryLoads`,
I'll look into merging it.

**Comment by aW4KeNiNG** [comment]
Synchronized with version 4.

**Comment by ibilon** [comment]
Oh there's no merge conflict anymore,

@jgranick what do you think? Having `NSAllowsArbitraryLoads` as default doesn't seem good.

**Comment by jgranick** [comment]
I apologize for delaying on merging a more complex nuanced solution for this. I've taken inspiration from your original approach, but implemented `<config:ios allow-insecure-http="" />` as an optional value. The tag can be defined multiple times for multiple domains, or once with "false" to disable insecure HTTP. Otherwise, a value of "*" or "true" is handled as the default, which is to allow all HTTP requests :smile:

**Pull request closed without merging**
