### PR TITLE
Display preloader progress for packed asset libraries.

### PR DESCRIPTION
**Pull request by justin-espedal**
Before this change, packed asset libraries don't incrementally update the preloader progress bar. This can make it seem like loading has stalled, especially on online targets with large asset packs being delivered over slow connections.

With this change, the download progress of the asset pack is tracked. Additionally, the unpacking progress of each individual asset in the pack is also tracked, though it's assumed to be a much smaller portion of the total time spent loading the asset pack.

Since audio files are not included in packet asset libraries, audio files are loaded separately from other asset types, the same way they would be loaded in a non-packed asset library.

### CODE REVIEW

**Comment by player-03** [comment]
~~Can you update this request to target 8.1.0-Dev?~~

**Comment by player-03** [comment]
The code looks good at a glance, but I have no actual experience with packed asset libraries, so I can't verify it.

**Comment by joshtynjala** [comment]
> The code looks good at a glance, but I have no actual experience with packed asset libraries, so I can't verify it.

Same

**Comment by zanzlanz** [comment]
Anecdotally, I applied these changes to my environment, and it works as I was hoping. It allows me to track preload progress when using packed assets, whereas before it was not possible.

Would love to see this merged.

**Pull request merged**
